"""Bounded, deterministic interpretation. Returned text is transient, never storage data."""

import re
import unicodedata
from dataclasses import dataclass


CLARIFICATION_RESPONSE = (
    "I couldn't clearly understand that WebPortal question. Could you rephrase it?"
)
# Reviewed terminology from the approved WebPortal sections. No arbitrary noun correction.
VARIANTS = {
    "craete": "create", "prject": "project", "proejct": "project",
    "parcl": "parcel", "addres": "address", "opton": "option",
    "explian": "explain", "logni": "login", "buidling": "building",
    "projcts": "projects", "webprotal": "WebPortal",
}
FOLLOW_UP = re.compile(
    r"^(?:(?:can|could|would) you |please )?(?:explain(?: (?:this|that)(?: option)?)?|"
    r"tell me more|what about that|where is it|what next|what happens next)[?.! ]*$", re.I
)
DOMAIN = re.compile(
    r"\b(?:webportal|projects?|apn|parcel|building address|login|owner title)\b", re.I
)
LANGUAGE = frozenset(
    "i you we my the a an is are can could how what where when why does do please "
    "explain tell show help configure support settings information access create start "
    "make enter login address project projects parcel option list password username".split()
)


@dataclass(frozen=True)
class Understanding:
    query: str
    clarification: bool = False
    typo_correction_used: bool = False


def normalize_language(message: str) -> Understanding:
    # Context wrappers are generated by M9; normalize only the current question before wrapping.
    text = unicodedata.normalize("NFKC", message)
    text = re.sub(r"\s+", " ", text).strip()
    corrected = False

    def replace(match):
        nonlocal corrected
        token = match.group()
        replacement = VARIANTS.get(token.casefold())
        if replacement:
            corrected = True
            return replacement
        return token

    text = re.sub(r"\b\w+\b", replace, text)
    # Shorthand only in an explicit reference phrase, never arbitrary names or nouns.
    text = re.sub(r"\bcan u\b", "can you", text, flags=re.I)
    text = re.sub(r"\bdat option\b", "that option", text, flags=re.I)
    # Approved feature alias, not an acronym definition or a new factual claim.
    text = re.sub(r"\bparcel info\b", "APN / Parcel Number information", text, flags=re.I)
    if DOMAIN.search(text):
        text = re.sub(r"^(?:hey(?: yo)?|hi|hello)[,! ]+", "", text, flags=re.I)
        text = re.sub(r"^(?:please[, ]+)?tell me (?=(?:where|how|what)\b)", "", text, flags=re.I)
    text = re.sub(r"([?!.,])\1+", r"\1", text)
    tokens = re.findall(r"[a-z]+", text.casefold())
    unclear = bool(FOLLOW_UP.fullmatch(text)) or (
        bool(text) and not DOMAIN.search(text) and not (set(tokens) & LANGUAGE)
        and (not tokens or sum(len(t) > 2 and not re.search(r"[aeiouy]", t)
                              for t in tokens) > len(tokens) / 2)
    )
    return Understanding(text, unclear, corrected)
